-- MySQL Script generated by MySQL Workbench
-- 09/12/16 12:01:27
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Apotek
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Apotek` ;

-- -----------------------------------------------------
-- Schema Apotek
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Apotek` DEFAULT CHARACTER SET utf8 ;
USE `Apotek` ;

-- -----------------------------------------------------
-- Table `Apotek`.`Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Apotek`.`Product` ;

CREATE TABLE IF NOT EXISTS `Apotek`.`Product` (
  `ProductNumber` INT NOT NULL,
  `Name` VARCHAR(100) NULL,
  `Description` VARCHAR(250) NULL,
  `Stock` INT NULL,
  `Price` DECIMAL(10) NULL,
  `Prescription` TINYINT(1) NULL,
  PRIMARY KEY (`ProductNumber`),
  UNIQUE INDEX `ProductNumber_UNIQUE` (`ProductNumber` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Apotek`.`Zipcode`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Apotek`.`Zipcode` ;

CREATE TABLE IF NOT EXISTS `Apotek`.`Zipcode` (
  `Zipcode` INT NOT NULL,
  `Name` VARCHAR(100) NULL,
  PRIMARY KEY (`Zipcode`),
  UNIQUE INDEX `Zipcode_UNIQUE` (`Zipcode` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Apotek`.`Roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Apotek`.`Roles` ;

CREATE TABLE IF NOT EXISTS `Apotek`.`Roles` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NULL,
  `AccessLevel` INT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Apotek`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Apotek`.`User` ;

CREATE TABLE IF NOT EXISTS `Apotek`.`User` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(100) NULL,
  `LastName` VARCHAR(100) NULL,
  `CPR` INT(10) NULL,
  `Password` VARCHAR(100) NULL,
  `Address` VARCHAR(100) NULL,
  `Zipcode_Zipcode` INT NOT NULL,
  `Roles_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `Zipcode_Zipcode`, `Roles_ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC),
  INDEX `fk_User_Zipcode1_idx` (`Zipcode_Zipcode` ASC),
  INDEX `fk_User_Roles1_idx` (`Roles_ID` ASC),
  CONSTRAINT `fk_User_Zipcode1`
    FOREIGN KEY (`Zipcode_Zipcode`)
    REFERENCES `Apotek`.`Zipcode` (`Zipcode`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_Roles1`
    FOREIGN KEY (`Roles_ID`)
    REFERENCES `Apotek`.`Roles` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Apotek`.`Prescription`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Apotek`.`Prescription` ;

CREATE TABLE IF NOT EXISTS `Apotek`.`Prescription` (
  `idPrescription` INT NOT NULL AUTO_INCREMENT,
  `User_ID` INT NOT NULL,
  `User_Zipcode_Zipcode` INT NOT NULL,
  PRIMARY KEY (`idPrescription`, `User_ID`, `User_Zipcode_Zipcode`),
  UNIQUE INDEX `idPrescription_UNIQUE` (`idPrescription` ASC),
  INDEX `fk_Prescription_User1_idx` (`User_ID` ASC, `User_Zipcode_Zipcode` ASC),
  CONSTRAINT `fk_Prescription_User1`
    FOREIGN KEY (`User_ID` , `User_Zipcode_Zipcode`)
    REFERENCES `Apotek`.`User` (`ID` , `Zipcode_Zipcode`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Apotek`.`Product_has_Prescription`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Apotek`.`Product_has_Prescription` ;

CREATE TABLE IF NOT EXISTS `Apotek`.`Product_has_Prescription` (
  `Product_ProductNumber` INT NOT NULL,
  `Prescription_idPrescription` INT NOT NULL,
  PRIMARY KEY (`Product_ProductNumber`, `Prescription_idPrescription`),
  INDEX `fk_Product_has_Prescription_Prescription1_idx` (`Prescription_idPrescription` ASC),
  INDEX `fk_Product_has_Prescription_Product_idx` (`Product_ProductNumber` ASC),
  CONSTRAINT `fk_Product_has_Prescription_Product`
    FOREIGN KEY (`Product_ProductNumber`)
    REFERENCES `Apotek`.`Product` (`ProductNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Product_has_Prescription_Prescription1`
    FOREIGN KEY (`Prescription_idPrescription`)
    REFERENCES `Apotek`.`Prescription` (`idPrescription`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
